### ISSUE TITLE
No module named 'py4j.java_collections'

### ISSUE THREAD

**Issue by Wildprogrammer** [adrian-evo/robotframework-sikulixlibrary#4]
mac os
jdk-16.0.1
python 3.9.5

hi，I have a problem with packaging.I use pyinstaller package to package the program。An error occurred when importing a class。I try to catch it
`
try:
    from SikuliXLibrary import SikuliXLibrary
except Exception as e:
    print(str(e))
    print('from SikuliXLibrary import SikuliXLibrary  failed!!!')
`
![image](https://user-images.githubusercontent.com/64333105/165016904-8eb633de-f90f-4109-ab50-e41c2bfae228.png)
Hope to get your help

**Comment by adrian-evo** [comment]
Hi, it seems this is related to pyinstaller and py4j packages, rather than sikulixlibrary module. I am not familiar with pyinstaller and I am not using it so unfortunately I cannot help. 

E.g. here some related question, not sure if it can help: https://stackoverflow.com/questions/57712179/no-module-named-py4j-java-collections-when-running-exe-created-using-pyinstall

**Comment by adrian-evo** [comment]
Nothing to fix.
